batch-size: 32
bos: <bos>
eos: <eos>
epochs: 97
kld-annealing: 0.025
learning-rate: 0.001
log-file: true
log-filename: '{save-dir}/train.log'
log-level: 0
log-stdout: false
optimizer: adam
pin-memory: true
samples: 0
save-period: '{epochs}'
seed: null
show-progress: true
shuffle: true
tensorboard: false
unk: <unk>
word-embed-path: "{%ludus-dir%}/datasets/glove/glove.840B.300d.tar"
word-embed-type: tar-format
word-pretrained: true
